version: '3.9'

services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app
      - .:/node_modules
  cache:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=mysecretpassword
  database:
    image: postgres:latest
    container_name: rusty_raptor_db
      - POSTGRES_USER=raptor
      - POSTGRES_PASSWORD=@dM!n
      - POSTGRES_DB=rusty_raptor
    restart: unless-stopped
    ports:
      - "5437:5437"